name: Tumin
title: Tumin | Demo
description: hello I make things with tech
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: TV
    url: /tv
  - title: Profile
    url: /profile
  - title: Feed
    url: /feed.xml
  
email: t.sheth33@gmail.com
# See: https://disqus.com/
disqus_username: tuminzee
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
